### ISSUE TITLE
yes icon , no dark background 

### ISSUE THREAD

**Issue by designercreativo** [PapirusDevelopmentTeam/papirus-filezilla-themes#15] opened 2020-05-03 10:21 UTC
Windows 10, I downloaded the package and placed the three folders inside the Resources folder.
Well I can choose the three themes, but only the icons change, no dark background. how to solve?

**Comment by SmartFinn** [comment] 2020-05-03 12:52
Duplicate of #12

**Closed as completed by SmartFinn** 2020-05-03 12:52 UTC
Labels: duplicate

**Comment by starspritechippy** [comment] 2020-07-19 22:37
#12 is no longer available, is there any hope?
